apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dotnet-deploy
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-dmpt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-dmpt
    app.kubernetes.io/part-of: e2e-dotnet
  name: devfile-sample-dotnet60-basic-dmpt
  namespace: e2e-demos-dwkg-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: devfile-dotnet-deploy
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-dmpt
  type: LoadBalancer
status:
  loadBalancer: {}
